import { route, index } from '@react-router/dev/routes';

export default [
  index('./page.jsx'),
  route('dashboard', './dashboard/page.jsx'),
  route('login', './login/page.jsx'),
  route('signup', './signup/page.jsx'),
  route('forgot-password', './forgot-password/page.jsx'),
  route('howitworks', './howitworks/page.jsx'),
  route('tip/:username', './tip/[username]/page.jsx'),
  route('api/auth/signup', './api/auth/signup/route.js'),
  route('api/auth/login', './api/auth/login/route.js'),
  route('api/auth/me', './api/auth/me/route.js'),
  route('api/auth/reset-password', './api/auth/reset-password/route.js'),
  route('api/auth/request-password-reset', './api/auth/request-password-reset/route.js'),
  route('api/auth/verify-password', './api/auth/verify-password/route.js'),
  route('api/tips/history', './api/tips/history/route.js'),
  route('api/tips/analytics', './api/tips/analytics/route.js'),
  route('api/tips/record', './api/tips/record/route.js'),
  route('api/tips/sponsored', './api/tips/sponsored/route.js'),
  route('api/user/check-username', './api/user/check-username/route.js'),
  route('api/user/:username', './api/user/[username]/route.js'),
  route('api/wallet/balance', './api/wallet/balance/route.js'),
  route('api/wallet/transactions', './api/wallet/transactions/route.js'),
  route('*', './__create/not-found.tsx'),
];